[workspace]
resolver = "2"

members = [ "common", "impereat", "macros"]
default-members = ["impereat", "macros"]

[workspace.dependencies]
common = { path = "common" }
impereat = { path = "impereat" }
macros = { path = "macros" }
variadics_please = "^1.1"