[package]
name = "imperat"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.87"
tokio = { version = "1.44.0", features = ["rt", "macros"] }
typemap_rev = "0.3.0"
variadics_please = "1.1.0"
